CREATE TABLE IF NOT EXISTS Calibration_Table
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    VESSEL_ID BIGINT                                              NOT NULL,
    TANK      VARCHAR(16)                                         NOT NULL,
    ULLAGE    FLOAT                                               NOT NULL,
    Cub1F     FLOAT                                               NOT NULL,
    Cub       FLOAT                                               NOT NULL,
    Cub1A     FLOAT                                               NOT NULL,
    Cub2A     FLOAT                                               NOT NULL,
    Cub3A     FLOAT                                               NOT NULL,
    Cub4A     FLOAT                                               NOT NULL
);

CREATE TABLE IF NOT EXISTS Cargo
(
    ID      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    NAME    VARCHAR                                          NOT NULL,
    TYPE    VARCHAR                                          NOT NULL,
    API     DECIMAL,
    DENSITY DECIMAL,
    TEMP_C  DECIMAL,
    TEMP_F  DECIMAL
);

CREATE TABLE IF NOT EXISTS Vessel
(
    ID            uuid PRIMARY KEY NOT NULL,
    NAME          VARCHAR(128)     NOT NULL,
    CALL_SIGN     VARCHAR          NOT NULL,
    FLAG_REGISTRY varchar          not null,
    TYPE          varchar          NOT NULL,
    LENGTH        decimal          NOT NULL,
    WIDTH         decimal          NOT NULL
);
/*
 TODO Fix Fill table from CSV using docker
 */
/*INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/1P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/1S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/2P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/2S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/3P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/3S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/4P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/4S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/5P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/5S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/6P.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/6S.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/SLP.csv');
INSERT INTO Calibration_table(ULLAGE, TANK, Cub1F, Cub, Cub1A, Cub2A, Cub3A, Cub4A) SELECT * FROM CSVREAD('crude-server/src/main/resources/static/SLS.csv');
*/