spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    jdbc-url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show-sql: false
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          time_zone: "UTC"