CREATE TABLE IF NOT EXISTS COT1P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT1S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT2P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT2S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT3P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT3S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT4P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT4S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT5P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT5S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT6P
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COT6S
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COTSLP
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS COTSLS
(
    ULLAGE FLOAT   NOT NULL,
    Cub1F  FLOAT NOT NULL,
    Cub    FLOAT NOT NULL,
    Cub1A  FLOAT NOT NULL,
    Cub2A  FLOAT NOT NULL,
    Cub3A  FLOAT NOT NULL,
    Cub4A  FLOAT NOT NULL
);

INSERT INTO COT1P SELECT * FROM CSVREAD('src/main/resources/static/1P.csv');
INSERT INTO COT1S SELECT * FROM CSVREAD('src/main/resources/static/1S.csv');
INSERT INTO COT2P SELECT * FROM CSVREAD('src/main/resources/static/2P.csv');
INSERT INTO COT2S SELECT * FROM CSVREAD('src/main/resources/static/2S.csv');
INSERT INTO COT3P SELECT * FROM CSVREAD('src/main/resources/static/3P.csv');
INSERT INTO COT3S SELECT * FROM CSVREAD('src/main/resources/static/3S.csv');
INSERT INTO COT4P SELECT * FROM CSVREAD('src/main/resources/static/4P.csv');
INSERT INTO COT4S SELECT * FROM CSVREAD('src/main/resources/static/4S.csv');
INSERT INTO COT5P SELECT * FROM CSVREAD('src/main/resources/static/5P.csv');
INSERT INTO COT5S SELECT * FROM CSVREAD('src/main/resources/static/5S.csv');
INSERT INTO COT6P SELECT * FROM CSVREAD('src/main/resources/static/6P.csv');
INSERT INTO COT6S SELECT * FROM CSVREAD('src/main/resources/static/6S.csv');
INSERT INTO COTSLP SELECT * FROM CSVREAD('src/main/resources/static/SLP.csv');
INSERT INTO COTSLS SELECT * FROM CSVREAD('src/main/resources/static/SLS.csv');